#BUILD STAGE: 
FROM node:10-alpine as builder
WORKDIR /usr/src/app
COPY ./backend/*.json ./
RUN npm install

#DELIVERY ARTIFACT STAGE: 
FROM node:10-alpine as delivery
WORKDIR /usr/src/app
ENV PATH /app/node_modules/.bin:$PATH
COPY --from=builder /usr/src/app/node_modules/ /usr/src/app/node_modules/
COPY . .
CMD ["node", "server.js"]
